"""
author: Japjot Singh Rajbans
date: December 19, 2024
Unemissionize, Carbon Emission Calculator and Reducer
"""

# Vehicle Emissions
def vehicle_emissions(car_liters) -> float:
    """
    This function will calculate vehicular emissions based on the amount of gas the person uses per month in liters, provided by the person.

    Args:
        car_liters (float): The amount of gas the person uses per month in liters.

    Returns:
        float: The total vehicular emissions in kg CO2 per year.
    """
    emissions_per_liter = 2.31 # kg CO2 per liter of gasoline (Source: https://natural-resources.canada.ca/sites/www.nrcan.gc.ca/files/oee/pdf/transportation/fuel-efficient-technologies/autosmart_factsheet_6_e.pdf)
    emissions = car_liters * emissions_per_liter * 12 # Multiplying by 12 to get yearly emissions
    return emissions

# Aeroplane Emissions
def aeroplane_emissions(flights_per_year) -> float:
    """
    This function will calculate the air travel emissions by taking in the number of flights the person every year takes, the average kilometers per flight, and the average CO2 emissions per kilometer, and multiply it.
    
    Args:
        flights_per_year (int): The number of flights the person takes per year.
    
    Returns:
        float: The total air travel emissions in kg CO2 per year.
    """
    CO2_per_km = 0.15 # Emissions (in kilograms) based on long-haul flights (Source: https://researchbriefings.files.parliament.uk/documents/CBP-8826/CBP-8826.pdf)
    avg_km_per_flight = 1500 # Average kilometers per flight (round trip) (Source: https://transport.ec.europa.eu/document/download/d7b5dd33-4083-4faa-8132-b6dc8b3a1c07_en)
    emissions = flights_per_year * avg_km_per_flight * CO2_per_km
    return emissions

# Non-Vegetarian Emissions
def non_veg_emissions(meat_consumption) -> float:
    """
    This function will calculate meat emissions by taking how much meat the person consumes and simply multiply it with emissions per kilogram of meat.
    
    Args:
        meat_consumption (float): The amount of meat the person consumes per year in kilograms.

    Returns:
        float: The total meat consumption emissions in kg CO2 per year.
    """
    emissions_per_kg = 27 # Emissions (in kilograms) per kilogram of meat (Source: https://static.ewg.org/reports/2011/meateaters/pdf/report_ewg_meat_eaters_guide_to_health_and_climate_2011.pdf)
    emissions = meat_consumption * emissions_per_kg
    return emissions

# Electricity Emissions
def electric_emissions(kwh_per_month) -> float:
    """
    This function will calculate the emissions generated by using electricity at your house. It will take kilowatt per month by the person and multiply it with emissions per kilowatt hour and 12 (to see the yearly emissions).

    Args:
        kwh_per_month (float): The amount of electricity the person uses per month in kilowatt-hours.

    Returns:
        float: The total electricity emissions in kg CO2 per year.
    """
    emissions_per_kwh = 0.92 # Emissions (in kilograms) per kilowatt-hour (Source: https://www.iea.org/reports/coal-in-net-zero-transitions/executive-summary)
    emissions = kwh_per_month * emissions_per_kwh * 12
    return emissions

# Suggesting reductions based on emissions
def suggest_reductions(car_emissions, air_travel_emissions, meat_emissions, electricity_emissions) -> list:
    """
    This function suggests ways to reduce emissions based on the highest sources of emissions.

    Args:
        car_emissions (float): The total car emissions in kg CO2 per year.
        air_travel_emissions (float): The total air travel emissions in kg CO2 per year.
        meat_emissions (float): The total meat consumption emissions in kg CO2 per year.
        electricity_emissions (float): The total electricity emissions in kg CO2 per year.

    Returns:
        list: A list of suggestions to reduce emissions.
    """
    reductions = [] # An empty list to store suggestions
    if car_emissions > 0: # Suggestion for car emissions
        reductions.append("You can reduce car emissions by using public transportation or an electric vehicle.")
    if air_travel_emissions > 0: # Suggestion for air travel emissions
        reductions.append("You can consider flying less or opting for trains for shorter trips.")
    if meat_emissions > 0: # Suggestion for meat consumption emissions
        reductions.append("Eating less meat can significantly reduce your carbon footprint, or you can start eating more vegetarian food!")
    if electricity_emissions > 0: # Suggestion for electricity emissions
        reductions.append("Using energy-efficient appliances or renewable energy sources can help reduce your emissions.")
    return reductions

# Reading data from a text file
def reading_data(data) -> tuple:
    """
    This function turns the list of information into the pieces needed for the calculations.

    Args:
        data (list): A list of strings containing the user's information.

    Returns:
        tuple: A tuple containing the user's name, car emissions, air travel emissions, meat emissions, and electricity emissions.
    """
    # Unpacking data
    name = data[0] # Name
    age = int(data[1]) # Age
    place = data[2] # Place
    has_car = data[3].lower() # Whether the person has a car or not
    car_emissions = 0 # Initializing car emissions

    # If the person has a car, it'll calculate car emissions
    if has_car == "yes":
        car_liters = float(data[4]) # Car liters
        kilometers_per_month = float(data[5]) # Kilometers per month
        car_emissions = vehicle_emissions(car_liters, kilometers_per_month) # Calculating car emissions

    # Doing the same for other emissions
    flights_per_year = int(data[6])
    air_travel_emissions = aeroplane_emissions(flights_per_year)
    meat_consumption = float(data[7])
    meat_emissions = non_veg_emissions(meat_consumption)
    kwh_per_month = float(data[8])
    electricity_emissions = electric_emissions(kwh_per_month)
    return name, car_emissions, air_travel_emissions, meat_emissions, electricity_emissions

# Main function
def main() -> None:
    """
    This is the main function that runs the Unemissionize program! It collects user input, processes the data, and provides output including suggestions for reducing carbon emissions.

    Args:
        None

    Returns:
        None
    """
    # Input
    filename = input("Hey there! Enter the filename to load data from, or press Enter to skip (this app only supports .txt file format): ").strip()
    
    # Input-Processing Hybrid
    if filename:
        with open(filename, mode="r") as f_in:
            data = f_in.readlines()
            data = [line.strip() for line in data]
        name, car_emissions, air_travel_emissions, meat_emissions, electricity_emissions = reading_data(data)
    
    else:
        name = input("Hey there! Welcome to Unemissionize! What's your name? ")
        age = int(input(f"Hey, {name}! How old are you? "))
        place = input("Alright! Where do you live (city/country)? ")
        print(f"Okay, then! Welcome to Unemissionize, {name}! :)")
        proceed = input("You will be asked some questions based on your age and place. Ready? ").lower()
        while proceed != "yes":
            proceed = input("You will be asked some questions based on your age and place. Ready? ").lower()
        print("Alright, then! Let's go!")
        
        # Processing
        has_car = input("Do you own a car? (yes/no): ").lower()
        car_emissions = 0
        if has_car == 'yes':
            car_liters = float(input("How much gas do you use per month (in liters)? "))
            car_emissions = vehicle_emissions(car_liters)

        flights_per_year = int(input("Now, it's time for flights! Based on an average round-trip distance of 1500 km, how many flights do you take per year (round trip)? "))
        air_travel_emissions = aeroplane_emissions(flights_per_year)

        meat_consumption = float(input("Next up, non-vegetarian! How many kilograms of meat do you consume per year? "))
        meat_emissions = non_veg_emissions(meat_consumption)

        kwh_per_month = float(input("Finally, electricity! How many kWh of electricity do you use per month? "))
        electricity_emissions = electric_emissions(kwh_per_month)

    total_emissions = car_emissions + air_travel_emissions + meat_emissions + electricity_emissions

    emissions_data = [car_emissions, air_travel_emissions, meat_emissions, electricity_emissions]
    emissions_labels = ["Car Emissions", "Air Travel Emissions", "Meat Consumption Emissions", "Electricity Usage Emissions"]
    max_index = 0
    # Finding the maximum emission source
    for i in range(1, len(emissions_data)):
        if emissions_data[i] > emissions_data[max_index]:
            max_index = i

    # Output
    print(f"\nWhew, {name}! That took some time!")
    print(f"Based on your information, your total carbon emissions per year are {total_emissions} kg CO2.")
    print(f"Your biggest source of emissions is {emissions_labels[max_index]} with {emissions_data[max_index]} kg CO2.")

    # Suggesting reductions
    reductions = suggest_reductions(car_emissions, air_travel_emissions, meat_emissions, electricity_emissions)
    print("\nBut don't worry! Just follow the suggestions below, and you are good to go! :)")
    for suggestion in reductions:
        print(f"- {suggestion}")

    # Saving to file
    save_to_file = input("Thank you so much for using Unemissionize! Do you want to save this data to a .txt file? (yes/no): ").lower()
    if save_to_file == 'yes':
        output_filename = input("Okie-dokie! Please enter the filename (without extension or .txt): ") + '.txt'
        with open(output_filename, mode="w") as f_out:
            f_out.write(f"Hello, {name}! Thank you for using Unemissionize!\n")
            f_out.write(f"Your total carbon emissions per year are {total_emissions} kg CO2.\n\n")
            f_out.write("But don't worry! Just follow the suggestions below, and you are good to go! :)\n")
            for suggestion in reductions:
                f_out.write(f"- {suggestion}\n")
        print(f"Thank you for using Unemissionize! Your results have been saved to your .txt file, {name}. Have a great day! :)")
    print(f"Thank you for using Unemissionize, {name}! Have a great day! :)")

# Finally, running the main function
if __name__ == "__main__":
    main()